[build]
  base = "."
  publish = "build/"
  command = "npm run build"

[[redirects]]
  from = "/url-here"
  to = "/new-url-here"
  status = 301
  force = true 

[[redirects]]
  from ="/locksmith"
  to = "/master-locksmith"
  status = 301
  force = true