// Content backup and export utilities
export class ContentBackupService {
  
  // Export all content to JSON file
  static exportContent(content) {
    const timestamp = new Date().toISOString().split('T')[0];
    const backupData = {
      timestamp: new Date().toISOString(),
      version: '3.0.0',
      content: content,
      metadata: {
        exportedBy: 'Kyle O\'Connor CMS',
        websiteUrl: 'https://kyleo.co.uk',
        contentSections: Object.keys(content).length
      }
    };

    const dataStr = JSON.stringify(backupData, null, 2);
    const dataBlob = new Blob([dataStr], { type: 'application/json' });
    
    const link = document.createElement('a');
    link.href = URL.createObjectURL(dataBlob);
    link.download = `kyleo-website-backup-${timestamp}.json`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    
    return {
      success: true,
      filename: `kyleo-website-backup-${timestamp}.json`,
      timestamp: backupData.timestamp
    };
  }

  // Import content from JSON file
  static importContent(file) {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      
      reader.onload = (event) => {
        try {
          const backupData = JSON.parse(event.target.result);
          
          // Validate backup structure
          if (!backupData.content || !backupData.timestamp) {
            throw new Error('Invalid backup file format');
          }
          
          // Extract content
          const content = backupData.content;
          
          // Validate required sections
          const requiredSections = ['personal', 'expertise', 'social'];
          const missingSections = requiredSections.filter(section => !content[section]);
          
          if (missingSections.length > 0) {
            console.warn('Missing sections in backup:', missingSections);
          }
          
          resolve({
            success: true,
            content: content,
            metadata: backupData.metadata,
            importedAt: new Date().toISOString()
          });
          
        } catch (error) {
          reject({
            success: false,
            error: `Failed to parse backup file: ${error.message}`
          });
        }
      };
      
      reader.onerror = () => {
        reject({
          success: false,
          error: 'Failed to read backup file'
        });
      };
      
      reader.readAsText(file);
    });
  }

  // Create automatic backup to localStorage
  static createAutoBackup(content) {
    const timestamp = new Date().toISOString();
    const backupKey = `cms_backup_${timestamp.split('T')[0]}`;
    
    const backupData = {
      timestamp,
      content,
      autoGenerated: true
    };
    
    try {
      localStorage.setItem(backupKey, JSON.stringify(backupData));
      
      // Keep only last 7 days of auto-backups
      this.cleanupOldBackups();
      
      return {
        success: true,
        backupKey,
        timestamp
      };
    } catch (error) {
      console.error('Failed to create auto-backup:', error);
      return {
        success: false,
        error: error.message
      };
    }
  }

  // Get list of available backups
  static getAvailableBackups() {
    const backups = [];
    
    for (let i = 0; i < localStorage.length; i++) {
      const key = localStorage.key(i);
      if (key && key.startsWith('cms_backup_')) {
        try {
          const backupData = JSON.parse(localStorage.getItem(key));
          backups.push({
            key,
            timestamp: backupData.timestamp,
            date: new Date(backupData.timestamp).toLocaleDateString(),
            autoGenerated: backupData.autoGenerated || false
          });
        } catch (error) {
          console.error('Error reading backup:', key, error);
        }
      }
    }
    
    return backups.sort((a, b) => new Date(b.timestamp) - new Date(a.timestamp));
  }

  // Restore from backup
  static restoreBackup(backupKey) {
    try {
      const backupData = localStorage.getItem(backupKey);
      if (!backupData) {
        throw new Error('Backup not found');
      }
      
      const parsed = JSON.parse(backupData);
      return {
        success: true,
        content: parsed.content,
        timestamp: parsed.timestamp
      };
    } catch (error) {
      return {
        success: false,
        error: error.message
      };
    }
  }

  // Clean up old backups (keep last 7 days)
  static cleanupOldBackups() {
    const sevenDaysAgo = new Date();
    sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);
    
    for (let i = localStorage.length - 1; i >= 0; i--) {
      const key = localStorage.key(i);
      if (key && key.startsWith('cms_backup_')) {
        try {
          const backupData = JSON.parse(localStorage.getItem(key));
          const backupDate = new Date(backupData.timestamp);
          
          if (backupDate < sevenDaysAgo) {
            localStorage.removeItem(key);
          }
        } catch (error) {
          // Remove corrupted backup
          localStorage.removeItem(key);
        }
      }
    }
  }

  // Get storage usage info
  static getStorageInfo() {
    let totalSize = 0;
    let backupSize = 0;
    let backupCount = 0;
    
    for (let i = 0; i < localStorage.length; i++) {
      const key = localStorage.key(i);
      const item = localStorage.getItem(key);
      const itemSize = (item || '').length;
      
      totalSize += itemSize;
      
      if (key && key.startsWith('cms_backup_')) {
        backupSize += itemSize;
        backupCount++;
      }
    }
    
    return {
      totalSize: totalSize,
      backupSize: backupSize,
      backupCount: backupCount,
      availableSpace: (5 * 1024 * 1024) - totalSize, // 5MB limit estimation
      usagePercentage: Math.round((totalSize / (5 * 1024 * 1024)) * 100)
    };
  }
}